
[[main]]
  name = "Come√ße Aqui"
  url = "/docs/basic/introduction/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Tutorial"
  url = "/docs/tutorial/basic/introduction"
  weight = 30

